jvm_highcore_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  required_pr_labels: Cirrus JVM
  container:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
    cpu: 4
    memory: 8G
  matrix:
    - name: JVM high-core-count 2.13
      script: sbt '++ 2.13' testsJVM/test ioAppTestsJVM/test
    - name: JVM high-core-count 3
      script: sbt '++ 3' testsJVM/test ioAppTestsJVM/test

jvm_arm_highcore_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  required_pr_labels: Cirrus JVM
  arm_container:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_3.3.0
    cpu: 4
    memory: 8G
  matrix:
    - name: JVM ARM high-core-count 2.13
      script: sbt '++ 2.13' testsJVM/test ioAppTestsJVM/test
    - name: JVM ARM high-core-count 3
      script: sbt '++ 3' testsJVM/test ioAppTestsJVM/test

native_arm_task:
  only_if: $CIRRUS_TAG != '' || $CIRRUS_PR != ''
  required_pr_labels: Cirrus Native
  arm_container:
    dockerfile: .cirrus/Dockerfile
    cpu: 2
    memory: 8G
  matrix:
    - name: Native ARM 3
      script: sbt '++ 3' testsNative/test ioAppTestsNative/test
