pull_request_rules:
  - name: label typelevel-steward's PRs
    conditions:
      - author=typelevel-steward[bot]
    actions:
      label:
        add: [':robot:']
  - name: label typelevel-steward's update PRs
    conditions:
      - author=typelevel-steward[bot]
      - body~=labels:.*library-update
    actions:
      label:
        add: [dependencies]
  - name: label dependabots's PRs
    conditions:
      - author=dependabot[bot]
    actions:
      label:
        add: [':robot:']
  - name: automatically merge dependabot docs PRs
    conditions:
      - author=dependabot[bot]
      - check-success=Generate Microsite
      - base=docs
    actions:
      merge:
        method: merge
